### ISSUE TITLE
converting script

### ISSUE THREAD

**Issue by mgstar1021** [Vadbeg/colorization-coreml#2]
Hello, Thanks for your converting, and you're great, I want to know how you to convert it to coreml so can you share your script? Thanks again.

**Comment by Vadbeg** [comment]
Hi! For sure. Here is the link for ther conversion script. You need to place this script in the root directory of the [richzhang/colorization](https://github.com/richzhang/colorization) repository. Do not forget to change paths to testing images:)

https://gist.github.com/Vadbeg/965708ed9ed91b8b863f99b9df10f898
